# Dzień 17 - Pandas: braki danych i podstawy czyszczenia

## Zakres
- powtórka 'merge()' i LEFT JOIN
- czym są brakujące wartości 'NaN'
- wykrywanie braków za pomocą 'isna()'
- liczenie brakujących wartości za pomocą 'isna().sum()'
- uzupełnianie braków za pomocą 'fillna()'
- podejmowanie decyzji, kiedy brak danych można zastąpić konkretną wartością

## Zadanie 1 - Powtórka merge() i LEFT JOIN

In [6]:
import pandas as pd
produkty = {
    "id": [1, 2, 3, 4],
    "produkt": ["Laptop", "Monitor", "Klawiatura", "Mysz"],
    "cena": [3499.99, 899.99, 249.90, 129.99]
}

zamowienia = {
    "produkt_id": [1, 2, 1, 3],
    "liczba_sztuk": [2, 5, 3, 4]
}

df_produkty = pd.DataFrame(produkty)
df_zamowienia = pd.DataFrame(zamowienia)

df_polaczone = pd.merge (
    df_produkty,
    df_zamowienia,
    left_on="id",
    right_on="produkt_id",
    how="left"
)
df_polaczone

   id     produkt     cena  produkt_id  liczba_sztuk
0   1      Laptop  3499.99         1.0           2.0
1   1      Laptop  3499.99         1.0           3.0
2   2     Monitor   899.99         2.0           5.0
3   3  Klawiatura   249.90         3.0           4.0
4   4        Mysz   129.99         NaN           NaN

## Zadanie 2 - Wykrywanie brakujących wartości

In [8]:
df_polaczone.isna()

      id  produkt   cena  produkt_id  liczba_sztuk
0  False    False  False       False         False
1  False    False  False       False         False
2  False    False  False       False         False
3  False    False  False       False         False
4  False    False  False        True          True

## Zadanie 3 - Liczenie brakujących wartości

In [9]:
df_polaczone.isna().sum()

id              0
produkt         0
cena            0
produkt_id      1
liczba_sztuk    1
dtype: int64

## Zadanie 4 - Uzupełnianie brakujących wartości

In [10]:
df_polaczone["liczba_sztuk"] = df_polaczone["liczba_sztuk"].fillna(0)
df_polaczone.isna().sum()

id              0
produkt         0
cena            0
produkt_id      1
liczba_sztuk    0
dtype: int64

## Zadanie 5 - Interpretacja brakujących danych

### Wniosek
Jeżeli brak wartości w "liczba_sztuk" wynika z tego, że produkt nie występuje w tabeli zamówień, można zastąpić 'NaN' wartością '0' za pomocą 'fillna(0)'.
Nie każdy brak danych należy jednak automatycznie zastępować zerem. Decyzja zależy od znaczenia danej kolumny i kontekstu danych.